### ISSUE TITLE
Make shields runnable on a PaaS

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1848]
In https://github.com/badges/shields/pull/1742#issuecomment-407446963 I’ve proposed that our production hosting move to Zeit Now. Whether or not this happens, I’d like to make sure Shields is fully capable of running in a PaaS. We’re most of the way there already. Shields doesn't have a lot of state. Since last year we’ve run our staging server on Heroku, and @platan recently ran a copy of Shields on Zeit for #1708.

We have a few bits in Shields which expect a persistent file system. Our production server relies on deploy commits. Deploy commits are possible with a PaaS, though they violate one of the [12-factor principles](https://12factor.net/config), and are more difficult to manage. Now supports [secure, shared environment variables](https://zeit.co/docs/features/env-and-secrets#securing-env-variables-using-secrets) and I'd like to make it possible to use them.

There are three items that come to mind:

- [ ] ~~Analytics (already has redis support, but it needs tests because it's not used in production)~~
- [x] GitHub token persistence (work in #1205)
    - [x] Admin route #1813 #1886
    - [x] GithubApiProvider #1812
    - [x] Initialization code #1861 
    - [x] Refactor JSON persistence #1863 
    - [x] Extend to cloud DB or cloud storage #1906 #1939
- [x] Option to load server secrets from the environment #2626

I’d like to set up each of these in a way that doesn’t interfere with the current usage. That way things are in good shape, however we decide to proceed.

**Comment by paulmelnikow** [comment]
[Compose](https://www.compose.com/pricing#redis), which I've used before, has Redis with persistence starting at $18.50/month. [RedisLabs](https://redislabs.com/pricing/cloud/) has it for $7/month, or if we want it highly available, $9/month. We have the budget for this.

Alternatively, given the nature of this data which could be infrequently read and written, we could use something like S3 or Google Cloud Storage, which would be much cheaper. We only need to write tokens when they change, and we could write stats once every 30 or 60 seconds.

**Comment by paulmelnikow** [comment]
I discussed a bit with @chris48s offline about the possibility of basing some of this using a storage abstraction layer which self-hosters and the production servers could choose. The most widely adopted of these I know of for Node is [abstract-blob-store](https://github.com/maxogden/abstract-blob-store) which is not really an abstraction layer but an interface. Still, I think it could be a good choice for certain kinds of caching.

For the github tokens it might be preferable to use a database that supports atomic inserts and deletes so we don't risk losing data based on the order of writes. I'll proceed with that, unless anyone else has thoughts?

**Comment by espadrine** [comment]
Something I always wanted to do with tokens was use a distributed convergent in-memory store; I started https://github.com/espadrine/jsonsync with that in mind.

**Comment by paulmelnikow** [comment]
I like that interface a lot. It's similar to what I've done in #1939, which could easily be abstracted to an interface like this.

A centralized / hub-and-spoke setup is simple. Each server only needs to know about the hub. Existing servers don't need to be reconfigured or updated when additional servers come online.

Certainly P2P negotiation / discovery could be implemented, which could be an interesting engineering challenge, but not one that this project needs to solve.

It's simpler if the config can be specified in advance, immutably, avoiding extra state about other servers that needs to be kept up to date.

**Comment by paulmelnikow** [comment]
See discussion in #2621 and implementation in #2626 for a config overhaul which addresses PaaS.

**Comment by paulmelnikow** [comment]
This is getting really close! Analytics looks to be the last piece of code, and migrating some of the persistence into cloud Redis is the next step on the ops side.

**Comment by paulmelnikow** [comment]
Maybe we can drop the old analytics code after #3093 is done.

**Comment by timothyis** [comment]
@paulmelnikow if you have any questions about moving to Now, please don't hesitate to contact me or our team for any questions. 🙌

**Comment by paulmelnikow** [comment]
Looks like this is done!
