### ISSUE TITLE
Better modal popup

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2496]
I've been working on a major improvement to the modal popup which is basically an epic. I've been referencing it as #701, however #777, #1146, and #2427 are also included.

I'm opening this to track the feature in a way that gives a more transparency to the goalpost and the process.

Here's the behavior I'd like to implement:

1. Show individual fields on the modal popup for each part of the URL path.
2. Same for the query string.
3. Pre-populate the fields with the example.
4. Provide a **Clear** button and a **Reset** button.
5. Add UI elements for the remaining badge options, e.g. logo.
6. Provide a non-editable box (like the **URL** box now) which contains the full URL as it's built.
7. Show the live preview whenever all the fields are filled in.

These are some of the technical milestones:

- [x] Define the routes in a way that enables building a URL from individual fields (#2050)
- [ ] Convert `exampleUrl` to `pattern`, `namedParams`, and `staticPreview` (#1961)
    - [ ] Examples: #2407 #2409 #2444 #2447 #2478
    - [ ] Needed features: #2479
    - [x] Nice to have: #2497
- [x] Extract the service definitions in a way that enables the front end to know the fields (#2397)
- [x] Consume that format in the frontend and drop the old format (#2441)
- [x] Set up dev experience
    - [x] Add basic frontend tests #2490
    - [x] Adopt [styled-components](https://www.styled-components.com/) #2517
- [x] Add fields for the named params and the query params
- [ ] Add UI elements for the remaining badge options

Superceding: #701 #777 #1146 #2427
Also ref: #1311

**Comment by paulmelnikow** [comment]
Let's track the remaining UI elements in #2867 and the remaining static previews in #1961.
