### ISSUE TITLE
Investigate making code contributions easier with Gitpod

### ISSUE THREAD

**Issue by jankeromnes** [badges/shields#2772]
:clipboard: **Description**

Following up from https://github.com/badges/shields/pull/2697#issuecomment-452383403.

I would like to make life easier for potential new [shields.io](https://shields.io) contributors by implementing [gitpod.io](https://gitpod.io) support for Shields development. Disclaimer: I work on Gitpod.

This could provide newcomers (and also Shields maintainers) with pre-configured workspaces in the cloud, allowing them to get started instantly, without having to first set up a complete development environment themselves.

TODO:
- [x] Allow cloning any Shields branch or pull request in Gitpod
- [x] Automatically pre-run `npm install`
- [x] Automatically start the Shields server and open it in a live preview
  - ~~(Doesn't work yet, because the badge server on port 8080 refuses any requests with non-localhost domains, which Gitpod's preview pane tries to do)~~ fixed in #2773
  - [x] add `onOpen: open-preview` to port `8080` in `.gitpod.yml` in order to auto-open preview when the Shields server starts (but maybe wait for https://github.com/theia-ide/theia/pull/4096 to restore the white background in Gitpod's preview)
- [ ] ~~Pre-install [ImageMagick](https://www.imagemagick.org/script/download.php)~~ (maybe not useful)
- [x] Mention experimental Gitpod support in `README.md` to help newcomers get started (done in #2783)
- [ ] Enable pre-built branches & pull requests once Gitpod supports those (so that contributors & reviewers don't have to wait for `npm install && npm run build` to finish before getting started)
- [ ] Auto-format on Save with Prettier (see https://github.com/theia-ide/theia/issues/3338)
- [ ] Suggest useful Shields workflows & commands (once https://github.com/gitpod-io/gitpod/issues/247 is implemented)

Please let me know what you think of this idea, and if you know other setup/configuration things that should be automated for new contributors.

**Comment by paulmelnikow** [comment]
This sounds really neat!

Oops, you're supposed to be able to set the bind address on the command line, like `node server 8080 0.0.0.0`, though it looks like it's broken. I opened #2773 with a fix.

I think you could skip ImageMagick. It's only needed for the raster (i.e. .png, .gif, .jpg) badges. That's a fairly unusual use case and most people probably would not need it for development.

**Comment by jankeromnes** [comment]
Wow, thanks a lot for the quick fix! 💯 It looks good to me, I'll try it out.

Is there a way to use `node server 8080 0.0.0.0` through a convenient command like `npm start`?

https://github.com/badges/shields/blob/a58de5428140024429970ddbaf09d10906fcbe9e/package.json#L103-L106

Maybe there should be some sort of `npm start:public-server`?

**Comment by paulmelnikow** [comment]
Does Gitpod need it to be an npm script?

It's surprising, but Heroku, Zeit Now, our production VPS, and I think our docker config seem content with the server binding to localhost.

Probably we could find a way to do that if necessary.

**Comment by paulmelnikow** [comment]
The typical dev flow is both servers running on localhost. The web preview works on localhost:8080.

How is Gitpod configured? Is there a config file that would get checked into the repo? That might be the best place to define a command that can be tailored for this situation.
