### ISSUE TITLE
Finish the code reorg

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2832]
I've gotten a good bit of the way through the work of implementing #2698 but I'm running out of steam so thought I'd pause. I could pick it up later or maybe other folks would like to pick up what's left.

After #2829 and #2831 are merged here's what remains:

- [x] Refactor `services/categories.js`, probably by leaving the category defs there and moving the rest into `core/base-service` (#3100)
- [x] Refactor `services/index.js`, moving the loader to `core/base-service/loader.js` (#2861)
- [x] Moving "good" badge helpers from `lib/` to `services/` (#3101)
- [ ] Moving "bad" badge helpers into `lib/` to `core/legacy/`
- [ ] Anything else I missed

#2698 can be used as a reference.

**Comment by chris48s** [comment]
After we merged the last refactoring PR I realised that we didn't update https://github.com/badges/shields/blob/master/now.json to account for the new layout. Can we squeeze that change into #2829 or #2831 ahead of review.

**Comment by paulmelnikow** [comment]
Added to #2829.

**Comment by paulmelnikow** [comment]
I started moving more of the legacy helpers, though it seems like it makes more sense to close out the home stretch of refactors in the next couple weeks. This is generating a bunch of conflicts with those changes, and mostly involves changing code that we want to delete.

After #3162 and #3163, what's left is:

1. `badge-data.js` which can be removed as soon as the refactors are done
2. `load-logos.js`, `load-simple-icons.js`, `logos.js`, and `svg-helpers.js` which should be moved into the npm package. "Refactor logo resolution so it happens in the badge generator" is in the backlog though it doesn't have an issue yet. Probably makes sense to move it once instead of twice.
3. `server-secrets.js` which should be eliminated in favor of injecting the secrets through `BaseService.register()` That'll require touching all the service implementations and probably that should happen once instead of twice.

We could open new issues for 2 and 3 and close this out.

**Comment by paulmelnikow** [comment]
#3392 removes `badge-data.js`.

**Comment by paulmelnikow** [comment]
Item (2) has been listed as a dependency in #3370, so let's track that there.

For item (3) I opened #3393.

Closing!
