### ISSUE TITLE
Replace badge server onboard rasterization with rasterizing proxy

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3631]
As discussed in #3112 and badges/svg-to-image-proxy#25 we're in the process of deploying a new proxy server. This will replace the onboard generation of raster badges on the badge server which will redirect.

This is a feature that has real but relatively obscure use cases (https://github.com/badges/shields/issues/3112#issuecomment-468738270, https://github.com/badges/shields/issues/3112#issuecomment-480422502) and the simplification and performance benefits make it seem worth breaking this out.

It makes things slightly less convenient for self-hosting users who might need raster badges, though it is not hard to also self-host the rasterizer.

Our current usage 2.5M invocations will cost about $1/month (or less if the downstream cache handles a chunk of the load). I'm not sure how much execution time we should expect. I doubt the cost will add up but if it does we could reach out to Zeit about a donation.

Here are the steps to be taken:

- [x] Deploy rasterizing proxy to raster.shields.io
- [x] Make sure other people have access to deploy.
- [x] Document the production hosting. (#3643 badges/svg-to-image-proxy#27)
    - [ ] Design a better process and address security (#3647)
- [x] Get the server running stably.
- [ ] Update the main server to redirect the `.png` badges to the production URL of the proxy. (#3644)
- [ ] Remove the raster capability and its dependencies from the main server. (#3644)
- [ ] Document how to self-host the rasterizing proxy. (#3644)
    - [ ] Improve the self-hosting docs (#3648)

**Comment by paulmelnikow** [comment]
@henrypoydar @drdamour You both commented in #3112 that you have use cases for raster badges.

Could I ask you to test our new raster server? Instead of e.g. https://img.shields.io/npm/v/nock.png you can access it at https://raster.shields.io/npm/v/nock.png

**Comment by drdamour** [comment]
works well. tried trickier stuff like https://img.shields.io/badge/stuff-hello%20world-purple.svg?style=popout&logo=appveyor

kinda weird https://raster.shields.io/npm/v/nock.svg gives a raster back...i get why, probably a non issue but in my head i figured i'd just send everything through the proxy and just change the extension.

what's the options for self hosted?

**Comment by drdamour** [comment]
is cacheSeconds broken? i'm only ever getting the default, but was thinking that'd be a good one to test through the proxy since it's not body and header stuff

**Comment by paulmelnikow** [comment]
Thanks for trying it!

> kinda weird https://raster.shields.io/npm/v/nock.svg gives a raster back...i get why, probably a non issue but in my head i figured i'd just send everything through the proxy and just change the extension.

The raster use case is fringe, so we want to support it, but only for people who really need it, and there's no benefit to sending traffic through the proxy that doesn't need to be rasterized. Eventually we'll implement #2674 which means you'll be able to omit the extension from both URLs.

It could return an error given `.svg` instead, though I don't really see a reason to do that.

Hmm, there's no specific handling of `cacheSeconds`, though most of the cache-related headers are passed through on the proxied response. Can you indicate what behavior you're seeing and what you expect?

**Comment by paulmelnikow** [comment]
Re self-hosting: I think you should be able to `npm ci` and run `BASE_URL=https://path-to-shields/ npm start`.

**Comment by drdamour** [comment]
i'm just not seeing the cacheSeconds being honored on either raster. or img.  response header does not change.

k if extensions are removed then it won't be as weird

**Comment by paulmelnikow** [comment]
Can you give steps to reproduce / observed + expected headers?

**Comment by drdamour** [comment]
just as it's documented on the site https://shields.io/


?cacheSeconds=3600 | Set the HTTP cache lifetime (rules are applied to infer a default value on a per-badge basis, any values specified below the default will be ignored). The legacy name "maxAge" is also supported.
-- | --

**Comment by paulmelnikow** [comment]
The static badge ignores cacheSeconds. Which badge are you using?
