### ISSUE TITLE
GitLab Service Badge tracking

### ISSUE THREAD

**Issue by sunny0826** [badges/shields#8077]
## Purpose

Provide more GitLab badges and track the progress of these tasks. If you have other needs, please write them in the comments.

## Existing badges

- coverage
- license
- pipeline-status
- release
- tag

## Services Tracking list

- [ ] contributors
- [ ] code size
- [ ] repo size
- [ ] issue number(opened\closed\all)
- [ ] merger request number(opened\closed\all)
- [ ] milestone
- [ ] labels
- [ ] forks
- [ ] stars
- [ ] language
- [ ] last commit
- [ ] GitLab (`go.mod` \ `package.json` \ etc.) version

## References

- https://github.com/badges/shields/tree/master/services/gitlab

/cc @calebcartwright

**Comment by calebcartwright** [comment]
Thanks for writing these up!

**Comment by sunny0826** [comment]
### TBD

- [ ] Encapsulate `document` texts in one place

**Comment by Jieiku** [comment]
I have the badges working for gitlab: stars, contributors, last commit.

What I have not figured out is Open issues and closed issues...
for github it starts like this:

```
https://img.shields.io/github/issues-raw/
https://img.shields.io/github/issues-closed-raw/
```

What is the proper way to make those badges for gitlab? or is the feature not live yet?

**Comment by sunny0826** [comment]
> I have the badges working for gitlab: stars, contributors, last commit.
> 
> What I have not figured out is Open issues and closed issues... for github it starts like this:
> 
> ```
> https://img.shields.io/github/issues-raw/
> https://img.shields.io/github/issues-closed-raw/
> ```
> 
> What is the proper way to make those badges for gitlab? or is the feature not live yet?

This feature is available. You can customize your badge in [shields.io](https://shields.io/).

just like
```
https://img.shields.io/gitlab/stars/gitlab-org/gitlab
```

**Comment by Jieiku** [comment]
Ah, thanks for the link to the customizer, got it working by looking over this page: https://shields.io/category/issue-tracking

**Comment by Gabbar-v7** [comment]
The repo-size requires to have role of Reporter, Developer, Maintainer, or Owner on the repo. It isn't publicly available. Is there any work around?
https://docs.gitlab.com/api/projects/#retrieve-a-project

End point: https://gitlab.com/api/v4/projects/project?statistics=true

**Comment by Gabbar-v7** [comment]
Addition to the tracking list: 
- [ ] Labels with counts
